create sequence hibernate_sequence start 1 increment 1;
create table Room (id int8 not null, primary key (id));
create table t_grades (id int8 not null, description varchar(255), title varchar(255) not null, value int2 not null, student_id int8, subject_id int8, primary key (id));
create table t_groups (id int8 not null, description varchar(255), title varchar(255), primary key (id));
create table t_subjects (id int8 not null, name varchar(255) not null, grade_id int8, primary key (id));
create table t_users (id int8 not null, email varchar(255), fullName varchar(255), password varchar(255), role varchar(255), username varchar(255), primary key (id));
create table t_users_groups (users_id int8 not null, groups_id int8 not null);
create table TimeSlot (id int8 not null, description varchar(255), endTime time, startTime time, title varchar(255), group_id int8, room_id int8, subject_id int8, primary key (id));
create table TimeTable (id int8 not null, description varchar(255), title varchar(255), primary key (id));
create table TimeTable_TimeSlot (TimeTable_id int8 not null, timeSlots_id int8 not null);
alter table if exists t_users add constraint UK_1f8qpknpngd98342v0j2ceadc unique (email);
alter table if exists t_users add constraint UK_sp0e01od15gf4nu5ffu87qb9n unique (username);
alter table if exists TimeTable_TimeSlot add constraint UK_nx5h8g6ka0a8bq4tfv8ptfc2v unique (timeSlots_id);
alter table if exists t_grades add constraint FKjlfutrdmwjp6wfn7housavsk7 foreign key (student_id) references t_users;
alter table if exists t_grades add constraint FKqgid0d6nv6xp9tgi2k4w05urp foreign key (subject_id) references t_subjects;
alter table if exists t_subjects add constraint FK51ugqsxksykovhyrvqcvd4u50 foreign key (grade_id) references t_grades;
alter table if exists t_users_groups add constraint FKoybpvvh28q2qlfrii8b7rvbgs foreign key (groups_id) references t_groups;
alter table if exists t_users_groups add constraint FKgwi0iqh0r1wfpaibe6xr81eh9 foreign key (users_id) references t_users;
alter table if exists TimeSlot add constraint FKjh4qy9pley26ov40u6mj21sw0 foreign key (group_id) references t_groups;
alter table if exists TimeSlot add constraint FKrh0c8mn30597w26krh1k61g3b foreign key (room_id) references Room;
alter table if exists TimeSlot add constraint FKgumuf5m1mr2qtbdw9jufk394o foreign key (subject_id) references t_subjects;
alter table if exists TimeTable_TimeSlot add constraint FKdns8knoqxsohdokejxnxt4fad foreign key (timeSlots_id) references TimeSlot;
alter table if exists TimeTable_TimeSlot add constraint FKru0idhjs6rj2vo3o8y65gfbix foreign key (TimeTable_id) references TimeTable;
