alter table if exists t_grades drop constraint if exists FKjlfutrdmwjp6wfn7housavsk7;
alter table if exists t_grades drop constraint if exists FKqgid0d6nv6xp9tgi2k4w05urp;
alter table if exists t_subjects drop constraint if exists FK51ugqsxksykovhyrvqcvd4u50;
alter table if exists t_users_groups drop constraint if exists FKoybpvvh28q2qlfrii8b7rvbgs;
alter table if exists t_users_groups drop constraint if exists FKgwi0iqh0r1wfpaibe6xr81eh9;
alter table if exists TimeSlot drop constraint if exists FKjh4qy9pley26ov40u6mj21sw0;
alter table if exists TimeSlot drop constraint if exists FKrh0c8mn30597w26krh1k61g3b;
alter table if exists TimeSlot drop constraint if exists FKgumuf5m1mr2qtbdw9jufk394o;
alter table if exists TimeTable_TimeSlot drop constraint if exists FKdns8knoqxsohdokejxnxt4fad;
alter table if exists TimeTable_TimeSlot drop constraint if exists FKru0idhjs6rj2vo3o8y65gfbix;
drop table if exists Room cascade;
drop table if exists t_grades cascade;
drop table if exists t_groups cascade;
drop table if exists t_subjects cascade;
drop table if exists t_users cascade;
drop table if exists t_users_groups cascade;
drop table if exists TimeSlot cascade;
drop table if exists TimeTable cascade;
drop table if exists TimeTable_TimeSlot cascade;
drop sequence if exists hibernate_sequence;
